dev-version-ext = "pre"
pre-release-commit-message = "Release {{version}}"
pro-release-commit-message = "Bump version to {{version}}"
tag-prefix = "v"
tag-message = "Release {{prefix}}{{version}}"
upload-doc = false
pre-release-replacements = [
  {file="README.md", search="0.1.2", replace="{{version}}"},
  {file="release.toml", search="0.1.2", replace="{{version}}"},
]
