language: rust
script:
  - cargo test --all
  - cargo test --all --no-default-features --features "string-null-empty" 
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
